export const TYPES = {
  //QUIZ:
  SET_QUIZ: 'SET_QUIZ',
  FETCH_QUIZ_SAGA: 'FETCH_QUIZ_SAGA',

  //CONFIG:
  NEW_GAME_SAGA: 'NEW_GAME_SAGA',
  END_GAME_SAGA: 'END_GAME_SAGA',
  SELECT_QUIZ_OPTION_SAGA: 'SELECT_QUIZ_OPTION_SAGA',
  NEXT_QUIZ_SAGA: 'NEXT_QUIZ_SAGA',
  SET_QUIZ_STATUS: 'SET_QUIZ_STATUS',
  DAMAGE_LIFES: 'DAMAGE_LIFES',
  RESET_LIFES: 'RESET_LIFES',
  SCORE_UP: 'SCORE_UP',
  RESET_SCORE: 'RESET_SCORE',
  RESET_QUIZ: 'RESET_QUIZ',
  NEXT_QUIZ: 'NEXT_QUIZ',
  SET_LANG_A: 'SET_LANG_A',
  SET_LANG_B: 'SET_LANG_B',
  
  //TIMER:
  START_TIMER_SAGA: 'START_TIMER_SAGA',
  STOP_TIMER_SAGA: 'STOP_TIMER_SAGA',
  TICK_TIMER: 'TICK_TIMER',
  RESET_TIMER: 'RESET_TIMER',

};

export const DEFAULT = {
  TIMER: 10,
  TOTAL_LIFES: 3,
  SCORE_UP: 15,
  IS_SELECTING_OPTIONS: 'IS_SELECTING_OPTIONS',
  IS_PLAYING: 'IS_PLAYING',
  IS_VIEWING_STATS: 'IS_VIEWING_STATS',
}

export const LANGUAGES = {
  SPANISH: 'spanish',
  ENGLISH: 'english',
  JAPANESE_KANA: 'japaneseKana',
  JAPANESE_KANJI: 'japaneseKanji',
  JAPANESE_ROMAJI: 'japaneseRomaji',
}