export const TYPES = {
  SET_QUIZ: 'SET_QUIZ',
  SET_GAME_SAGA_REQUEST: 'SET_GAME_SAGA_REQUEST',
  SET_IS_STATS: 'SET_IS_STATS',
  
  //CONFIG:
  NEW_GAME_SAGA: 'NEW_GAME_SAGA',
  END_GAME_SAGA: 'END_GAME_SAGA',
  DAMAGE_LIFES: 'DAMAGE_LIFES',
  RESET_LIFES: 'RESET_LIFES',
  CHANGE_IS_PLAYING: 'CHANGE_IS_PLAYING',
  SCORE_UP: 'SCORE_UP',
  RESET_SCORE: 'RESET_SCORE',
  RESET_QUIZ: 'RESET_QUIZ',
  NEXT_QUIZ: 'NEXT_QUIZ',
  SET_LANG_A: 'SET_LANG_A',
  SET_LANG_B: 'SET_LANG_B',
  NEXT_QUIZ_SAGA: 'NEXT_QUIZ_SAGA',
  SELECT_QUIZ_OPTION_SAGA: 'SELECT_QUIZ_OPTION_SAGA',
  
  //TIMER:
  START_TIMER_SAGA: 'START_TIMER_SAGA',
  STOP_TIMER_SAGA: 'STOP_TIMER_SAGA',
  TICK_TIMER: 'TICK_TIMER',
  RESET_TIMER: 'RESET_TIMER',

};

export const DEFAULT = {
  TIMER: 10,
  TOTAL_LIFES: 3,
  SCORE_UP: 15,
}

export const LANGUAGES = {
  SPANISH: 'spanish',
  ENGLISH: 'english',
  JAPANESE_KANA: 'japaneseKana',
  JAPANESE_KANJI: 'japaneseKanji',
  JAPANESE_ROMAJI: 'japaneseRomaji',
}